const topics = [
  {
    id: 'kpop',
    name: 'K-Pop',
    emoji: '🎤',
    color: '#ff6b9d',
    gradient: 'linear-gradient(135deg, #ff6b9d, #c44dff)',
    description: 'Stan culture & idol knowledge',
    questions: [
      { q: "Which group released the mega-hit 'Dynamite' in 2020?", options: ["BLACKPINK", "BTS", "EXO", "TWICE"], answer: 1 },
      { q: "BLACKPINK's fandom name is?", options: ["BLINK", "ARMY", "ONCE", "REVELUV"], answer: 0 },
      { q: "Which solo artist released 'SOLO' in 2018?", options: ["Lisa", "Jennie", "Rosé", "Jisoo"], answer: 1 },
      { q: "What does 'maknae' mean in K-Pop?", options: ["Leader", "Oldest member", "Youngest member", "Main vocalist"], answer: 2 },
      { q: "Which group is known as 'Monster Rookies'?", options: ["aespa", "ITZY", "EXO", "NCT"], answer: 2 },
      { q: "BTS's fandom is called?", options: ["BLINK", "ARMY", "ONCE", "STAY"], answer: 1 },
      { q: "Which group released 'How You Like That'?", options: ["TWICE", "aespa", "BLACKPINK", "Red Velvet"], answer: 2 },
      { q: "TWICE's fandom name is?", options: ["ONCE", "BLINK", "CARAT", "STAY"], answer: 0 },
      { q: "Which idol is known as 'Human Gucci'?", options: ["V (BTS)", "Kai (EXO)", "Jimin (BTS)", "Sehun (EXO)"], answer: 0 },
      { q: "What year did BTS debut?", options: ["2010", "2011", "2013", "2015"], answer: 2 },
      { q: "Which group's album 'Map of the Soul: 7' topped charts worldwide?", options: ["EXO", "GOT7", "BTS", "MONSTA X"], answer: 2 },
      { q: "aespa's AI concept features virtual versions called?", options: ["æ-members", "avatars", "holograms", "clones"], answer: 0 },
      { q: "Which K-Pop group has the most YouTube subscribers?", options: ["BTS", "BLACKPINK", "TWICE", "EXO"], answer: 1 },
      { q: "Lisa is from which country?", options: ["Korea", "Japan", "Thailand", "China"], answer: 2 },
      { q: "Which BTS song became their first all-English single?", options: ["Butter", "Dynamite", "Permission to Dance", "Life Goes On"], answer: 1 }
    ]
  },
  {
    id: 'fashion',
    name: 'Fashion',
    emoji: '👗',
    color: '#ffd93d',
    gradient: 'linear-gradient(135deg, #ffd93d, #ff9a3c)',
    description: 'Style, trends & designer trivia',
    questions: [
      { q: "Which fashion house created the iconic 'little black dress'?", options: ["Dior", "Chanel", "Givenchy", "Versace"], answer: 1 },
      { q: "What does 'haute couture' literally mean?", options: ["High fashion", "High sewing", "Luxury brand", "French style"], answer: 1 },
      { q: "Which Italian brand is known for its interlocking G logo?", options: ["Gucci", "Givenchy", "Giorgio Armani", "Gabbana"], answer: 0 },
      { q: "The 'trench coat' was originally designed for?", options: ["Fashion shows", "Military use", "Cold weather", "Rain protection"], answer: 1 },
      { q: "Which city is NOT a major fashion capital?", options: ["Paris", "Milan", "Tokyo", "Sydney"], answer: 3 },
      { q: "Coco Chanel's first name was actually?", options: ["Coco", "Gabrielle", "Marie", "Cecile"], answer: 1 },
      { q: "Which brand is known for its red-soled shoes?", options: ["Jimmy Choo", "Manolo Blahnik", "Christian Louboutin", "Stuart Weitzman"], answer: 2 },
      { q: "What fabric is made from silkworm cocoons?", options: ["Cotton", "Linen", "Silk", "Wool"], answer: 2 },
      { q: "The 'LBD' in fashion stands for?", options: ["Latest Brand Design", "Little Black Dress", "Luxury Brand Detail", "London Bold Design"], answer: 1 },
      { q: "Which brand has the iconic 'double F' logo?", options: ["Fendi", "Ferragamo", "Fossil", "Furla"], answer: 0 },
      { q: "Denim jeans were originally made for?", options: ["Fashion shows", "Miners & workers", "Sailors", "Cowboys"], answer: 1 },
      { q: "Which designer created the iconic 'wrap dress'?", options: ["Diane von Furstenberg", "Calvin Klein", "Ralph Lauren", "Donna Karan"], answer: 0 },
      { q: "What is 'fast fashion'?", options: ["Quick runway shows", "Cheap, trend-driven clothing", "Athletic wear", "Digital fashion"], answer: 1 },
      { q: "The Birkin bag is made by which brand?", options: ["Louis Vuitton", "Chanel", "Hermès", "Prada"], answer: 2 },
      { q: "Which pattern is associated with Burberry?", options: ["Polka dots", "Stripes", "Plaid/tartan check", "Floral"], answer: 2 }
    ]
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    color: '#6bcb77',
    gradient: 'linear-gradient(135deg, #6bcb77, #00b4d8)',
    description: 'Athletics, records & champions',
    questions: [
      { q: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], answer: 1 },
      { q: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], answer: 2 },
      { q: "In tennis, what is a score of zero called?", options: ["Nil", "Zero", "Love", "Blank"], answer: 2 },
      { q: "The Olympics are held every how many years?", options: ["2", "3", "4", "5"], answer: 2 },
      { q: "Which sport uses a shuttlecock?", options: ["Tennis", "Squash", "Badminton", "Pickleball"], answer: 2 },
      { q: "How many holes are in a standard golf course?", options: ["9", "12", "18", "24"], answer: 2 },
      { q: "Which athlete has won the most Olympic gold medals?", options: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], answer: 1 },
      { q: "A 'hat trick' in soccer means?", options: ["3 goals by one player", "3 assists", "Saving 3 shots", "3 yellow cards"], answer: 0 },
      { q: "What is the diameter of a basketball hoop in inches?", options: ["14 inches", "16 inches", "18 inches", "20 inches"], answer: 2 },
      { q: "Which country invented the sport of cricket?", options: ["Australia", "India", "England", "South Africa"], answer: 2 },
      { q: "In swimming, what is the fastest stroke?", options: ["Breaststroke", "Backstroke", "Butterfly", "Freestyle"], answer: 3 },
      { q: "How long is a marathon in kilometers?", options: ["40km", "42.195km", "44km", "45km"], answer: 1 },
      { q: "Which sport is played at Wimbledon?", options: ["Cricket", "Golf", "Tennis", "Polo"], answer: 2 },
      { q: "The term 'slam dunk' originates from which sport?", options: ["Volleyball", "Basketball", "Handball", "Water polo"], answer: 1 },
      { q: "How many players are in a volleyball team on the court?", options: ["5", "6", "7", "8"], answer: 1 }
    ]
  },
  {
    id: 'movies',
    name: 'Movies',
    emoji: '🎬',
    color: '#4cc9f0',
    gradient: 'linear-gradient(135deg, #4cc9f0, #4361ee)',
    description: 'Cinema, icons & box office hits',
    questions: [
      { q: "Which movie features the quote 'I'll be back'?", options: ["RoboCop", "The Terminator", "Predator", "Total Recall"], answer: 1 },
      { q: "Who directed 'Titanic' (1997)?", options: ["Steven Spielberg", "James Cameron", "Ridley Scott", "Christopher Nolan"], answer: 1 },
      { q: "Which film won the first ever Academy Award for Best Picture?", options: ["Gone with the Wind", "Wings", "It Happened One Night", "All Quiet"], answer: 1 },
      { q: "The lion in 'The Lion King' is named?", options: ["Mufasa", "Simba", "Nala", "Scar"], answer: 1 },
      { q: "Which movie has the highest box office gross of all time?", options: ["Avengers: Endgame", "Titanic", "Avatar", "Star Wars"], answer: 2 },
      { q: "Who played Iron Man in the MCU?", options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], answer: 2 },
      { q: "'To infinity and beyond' is a quote from?", options: ["Toy Story", "A Bug's Life", "Monsters Inc", "Finding Nemo"], answer: 0 },
      { q: "Which studio produced the 'Harry Potter' film series?", options: ["Universal", "Disney", "Warner Bros", "Paramount"], answer: 2 },
      { q: "In which movie does a character say 'Why so serious?'", options: ["Batman", "The Dark Knight", "Joker", "Batman Returns"], answer: 1 },
      { q: "Which actress played Katniss in 'The Hunger Games'?", options: ["Emma Watson", "Shailene Woodley", "Jennifer Lawrence", "Lupita Nyong'o"], answer: 2 },
      { q: "Which Disney movie features the song 'Let It Go'?", options: ["Tangled", "Brave", "Moana", "Frozen"], answer: 3 },
      { q: "Who voices Shrek in the animated movies?", options: ["Jim Carrey", "Mike Myers", "Eddie Murphy", "Jack Black"], answer: 1 },
      { q: "Which film features the fictional country of Wakanda?", options: ["Black Panther", "Avengers", "Captain America", "Thor"], answer: 0 },
      { q: "The 'Fast & Furious' franchise started in which year?", options: ["1999", "2001", "2003", "2005"], answer: 1 },
      { q: "Who directed the 'Inception' (2010)?", options: ["Ridley Scott", "J.J. Abrams", "Christopher Nolan", "Denis Villeneuve"], answer: 2 }
    ]
  },
  {
    id: 'food',
    name: 'Food',
    emoji: '🍕',
    color: '#ff9a3c',
    gradient: 'linear-gradient(135deg, #ff9a3c, #ff6b6b)',
    description: 'Cuisine, flavors & food facts',
    questions: [
      { q: "Which country is the origin of sushi?", options: ["China", "Korea", "Japan", "Thailand"], answer: 2 },
      { q: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Lime", "Onion"], answer: 1 },
      { q: "Pizza originated in which country?", options: ["USA", "France", "Italy", "Greece"], answer: 2 },
      { q: "What gives bread its fluffy texture?", options: ["Salt", "Sugar", "Yeast", "Butter"], answer: 2 },
      { q: "Which spice is known as the most expensive in the world?", options: ["Vanilla", "Cardamom", "Saffron", "Truffle"], answer: 2 },
      { q: "Kimchi is a traditional dish from which country?", options: ["Japan", "China", "Vietnam", "Korea"], answer: 3 },
      { q: "What type of pasta is shaped like small rice grains?", options: ["Penne", "Orzo", "Fusilli", "Farfalle"], answer: 1 },
      { q: "Which fruit is known as the 'king of fruits'?", options: ["Mango", "Durian", "Jackfruit", "Lychee"], answer: 1 },
      { q: "Croissants originated in which country?", options: ["France", "Austria", "Belgium", "Switzerland"], answer: 1 },
      { q: "What is the primary ingredient in hummus?", options: ["Lentils", "Black beans", "Chickpeas", "Kidney beans"], answer: 2 },
      { q: "Which country drinks the most tea per capita?", options: ["China", "India", "Turkey", "England"], answer: 2 },
      { q: "Tiramisu is a dessert from which country?", options: ["France", "Spain", "Italy", "Portugal"], answer: 2 },
      { q: "What does 'umami' describe?", options: ["Spicy taste", "Sweet taste", "Savory/meaty taste", "Sour taste"], answer: 2 },
      { q: "Which nut is used to make marzipan?", options: ["Walnut", "Hazelnut", "Almond", "Cashew"], answer: 2 },
      { q: "Pad Thai is a dish from which country?", options: ["Vietnam", "Thailand", "Indonesia", "Malaysia"], answer: 1 }
    ]
  },
  {
    id: 'science',
    name: 'Science',
    emoji: '🔬',
    color: '#c44dff',
    gradient: 'linear-gradient(135deg, #c44dff, #4361ee)',
    description: 'Facts, discoveries & wonders',
    questions: [
      { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
      { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
      { q: "What planet is known as the Red Planet?", options: ["Jupiter", "Saturn", "Venus", "Mars"], answer: 3 },
      { q: "What is the speed of light (approx)?", options: ["200,000 km/s", "300,000 km/s", "400,000 km/s", "500,000 km/s"], answer: 1 },
      { q: "DNA stands for?", options: ["Deoxyribonucleic Acid", "Diribose Nucleic Acid", "Dynamic Nucleic Acid", "Double Nucleic Array"], answer: 0 },
      { q: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2 },
      { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], answer: 2 },
      { q: "How many elements are on the periodic table?", options: ["108", "112", "118", "124"], answer: 2 },
      { q: "What force keeps planets in orbit around the sun?", options: ["Magnetism", "Gravity", "Nuclear force", "Friction"], answer: 1 },
      { q: "The human body is made up of approximately how much water?", options: ["45%", "55%", "60%", "70%"], answer: 2 },
      { q: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
      { q: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2 },
      { q: "Sound travels fastest through which medium?", options: ["Air", "Water", "Vacuum", "Solid"], answer: 3 },
      { q: "What is the most abundant gas in Earth's atmosphere?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 2 },
      { q: "Which scientist proposed the theory of general relativity?", options: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Stephen Hawking"], answer: 2 }
    ]
  }
];
