const quizData = {
  kpop: {
    name: "K-Pop", emoji: "🎤", color: "#FF6B9D", accent: "#FF0066",
    bg: "linear-gradient(135deg, #FF6B9D, #C44569)", description: "Stan culture & idol trivia",
    easy: [
      { q: "Which K-pop group is known for the song 'Dynamite'?", options: ["EXO", "BTS", "BIGBANG", "SHINee"], answer: 1 },
      { q: "BLACKPINK is signed under which label?", options: ["SM Entertainment", "JYP Entertainment", "YG Entertainment", "HYBE"], answer: 2 },
      { q: "What is the fandom name for BTS fans?", options: ["Blinks", "Army", "Once", "Reveluv"], answer: 1 },
      { q: "Which group has members Lisa, Jennie, Rosé, and Jisoo?", options: ["TWICE", "BLACKPINK", "aespa", "Red Velvet"], answer: 1 },
      { q: "What does 'bias' mean in K-pop?", options: ["A music producer", "Your favorite member", "A dance move", "A comeback album"], answer: 1 },
      { q: "Which group popularized 'Gangnam Style'?", options: ["2NE1", "Super Junior", "PSY", "BIGBANG"], answer: 2 },
      { q: "TWICE is from which entertainment company?", options: ["SM", "YG", "JYP", "HYBE"], answer: 2 },
      { q: "What does 'maknae' mean?", options: ["Leader", "Vocalist", "Youngest member", "Dancer"], answer: 2 },
      { q: "Which group is known for 'Butter'?", options: ["GOT7", "BTS", "MONSTA X", "2PM"], answer: 1 },
      { q: "What is a K-pop 'comeback'?", options: ["Return from military", "New music release", "Award win", "Fan meeting"], answer: 1 },
      { q: "What year did BTS debut?", options: ["2010", "2011", "2013", "2015"], answer: 2 },
      { q: "Which group has a member named Tzuyu?", options: ["BLACKPINK", "TWICE", "Red Velvet", "IVE"], answer: 1 },
      { q: "What does 'daesang' mean?", options: ["Best new artist", "Grand prize", "Best song", "Fan favorite"], answer: 1 },
      { q: "Which K-pop group has the fandom name 'Blinks'?", options: ["TWICE", "aespa", "BLACKPINK", "IVE"], answer: 2 },
      { q: "What is a 'sasaeng'?", options: ["A music producer", "An obsessive fan", "A dance move", "A fan club"], answer: 1 }
    ],
    medium: [
      { q: "Which BTS member released the solo song 'Singularity'?", options: ["Jimin", "V", "Suga", "J-Hope"], answer: 1 },
      { q: "What is the name of BLACKPINK's first full studio album?", options: ["Kill This Love", "The Album", "Born Pink", "Square Up"], answer: 1 },
      { q: "Which SM Entertainment group debuted in 2012 with 'MAMA'?", options: ["SHINee", "NCT", "EXO", "Super Junior"], answer: 2 },
      { q: "What concept is aespa known for?", options: ["Virtual avatars called 'ae'", "Military concept", "Retro 80s", "Underwater theme"], answer: 0 },
      { q: "Which member of Stray Kids is also the group's main producer?", options: ["Felix", "Bang Chan", "Hyunjin", "Han"], answer: 1 },
      { q: "What is the name of TWICE's official fandom?", options: ["Carat", "Once", "Stay", "Midzy"], answer: 1 },
      { q: "Which group released 'Love Scenario' in 2018?", options: ["EXO", "iKON", "WINNER", "BIGBANG"], answer: 1 },
      { q: "Which HYBE group debuted in 2022 with 'FEARLESS'?", options: ["TXT", "ENHYPEN", "LE SSERAFIM", "NewJeans"], answer: 2 },
      { q: "What year did BIGBANG debut?", options: ["2004", "2006", "2008", "2010"], answer: 1 },
      { q: "Which JYP group debuted with 'Dalla Dalla'?", options: ["TWICE", "ITZY", "NMIXX", "Wonder Girls"], answer: 1 },
      { q: "Who is the leader of EXO?", options: ["Baekhyun", "Kai", "Suho", "Sehun"], answer: 2 },
      { q: "Which group's fandom is called 'Carat'?", options: ["SEVENTEEN", "GOT7", "MONSTA X", "SHINee"], answer: 0 },
      { q: "Which group holds the record for most weeks at #1 on the Gaon Album Chart?", options: ["EXO", "BTS", "TWICE", "BIGBANG"], answer: 1 },
      { q: "IVE's Wonyoung previously debuted in which group?", options: ["LOONA", "IZONE", "fromis_9", "Cherry Bullet"], answer: 1 },
      { q: "NewJeans is under which sub-label of HYBE?", options: ["BELIFT LAB", "BigHit Music", "ADOR", "SOURCE MUSIC"], answer: 2 }
    ],
    hard: [
      { q: "Before debuting, BTS's full Korean name 'Bangtan Sonyeondan' literally translates to what?", options: ["Beyond the Scene", "Bulletproof Boy Scouts", "Burning Youth Stars", "Brave Young Generation"], answer: 1 },
      { q: "Which BLACKPINK member trained the longest before debut?", options: ["Jisoo", "Jennie", "Rosé", "Lisa"], answer: 1 },
      { q: "NCT's system allows unlimited members — what specific concept defines their sub-unit system?", options: ["Open concept with city-based units", "Rotate and Connect through fixed units", "Infinite expansion with no fixed members", "Studio vs. performance units"], answer: 0 },
      { q: "SHINee's Jonghyun released a solo album titled what in 2015?", options: ["Base", "She Is", "Story Op.1", "Inspiration"], answer: 0 },
      { q: "Which group introduced the 'performance unit / vocal unit / hip-hop unit' sub-unit concept?", options: ["EXO", "SEVENTEEN", "GOT7", "2PM"], answer: 1 },
      { q: "Which K-pop group holds the Guinness record for most viewers for a YouTube MV premiere?", options: ["BLACKPINK", "BTS", "TWICE", "aespa"], answer: 0 },
      { q: "Kang Daniel's solo debut after leaving Wanna One was under which self-founded label?", options: ["KONNECT Entertainment", "Stone Music", "Off The Record", "Sublime Artist Agency"], answer: 0 },
      { q: "What was H.O.T's original fandom club — considered the first organized K-pop fandom?", options: ["Club H.O.T", "White Angels", "Candy", "S.M. Family"], answer: 1 },
      { q: "Which concept defines SMCU (SM Culture Universe) connecting multiple SM groups narratively?", options: ["Shared fictional universe with crossover lore", "Reality TV integration", "NFT-based storytelling", "Metaverse concerts only"], answer: 0 },
      { q: "Which group's concept involves a fictional 'nævis' AI system that communicates with members?", options: ["BLACKPINK", "aespa", "TWICE", "Red Velvet"], answer: 1 },
      { q: "Which year did the first M Countdown episode air, establishing the modern idol chart show format?", options: ["1999", "2004", "2007", "2010"], answer: 1 },
      { q: "G-Dragon's solo mini-album 'Heartbreaker' controversially sampled which international artist's track?", options: ["Flo Rida's 'Right Round'", "Lady Gaga's 'Just Dance'", "Kanye West's 'Heartless'", "Ne-Yo's 'Closer'"], answer: 0 },
      { q: "Which label system pioneered 'in-house songwriting' as idol groups composing their own full albums?", options: ["Big Hit (BTS)", "SM (TVXQ)", "YG (BIGBANG)", "JYP (2PM)"], answer: 2 },
      { q: "What term describes the practice of 'light stick wars' where fandoms create coordinated color displays at concerts?", options: ["Penlight choreography", "Ocean (바다)", "Fanchant", "Satoori battle"], answer: 1 },
      { q: "Which idol group was the first K-pop act to perform at the Grammy Awards ceremony?", options: ["BTS", "BLACKPINK", "EXO", "CL"], answer: 0 }
    ]
  },
  fashion: {
    name: "Fashion", emoji: "👗", color: "#A78BFA", accent: "#7C3AED",
    bg: "linear-gradient(135deg, #A78BFA, #7C3AED)", description: "Style, trends & designers",
    easy: [
      { q: "Which fashion house is known for the 'double C' logo?", options: ["Gucci", "Chanel", "Christian Dior", "Cartier"], answer: 1 },
      { q: "Which brand created the iconic Birkin bag?", options: ["Louis Vuitton", "Chanel", "Hermès", "Prada"], answer: 2 },
      { q: "What is 'haute couture'?", options: ["Ready-to-wear fashion", "High-end custom fashion", "Vintage clothing", "Street style"], answer: 1 },
      { q: "Which Italian brand is known for red-soled shoes?", options: ["Prada", "Versace", "Christian Louboutin", "Ferragamo"], answer: 2 },
      { q: "What city is considered the fashion capital of the world?", options: ["London", "Milan", "Paris", "New York"], answer: 2 },
      { q: "Which brand has the iconic interlocking G logo?", options: ["Givenchy", "Gucci", "Armani", "Gaultier"], answer: 1 },
      { q: "What decade did the miniskirt become popular?", options: ["1950s", "1960s", "1970s", "1980s"], answer: 1 },
      { q: "Which designer popularized the 'little black dress' concept?", options: ["Versace", "Coco Chanel", "Valentino", "Givenchy"], answer: 1 },
      { q: "What fabric is traditionally used in denim?", options: ["Cotton", "Polyester", "Silk", "Linen"], answer: 0 },
      { q: "What material comes from silkworms?", options: ["Cotton", "Wool", "Silk", "Linen"], answer: 2 },
      { q: "What does 'fast fashion' refer to?", options: ["Expensive luxury fashion", "Quick trend-based cheap clothing", "Athletic wear", "Sustainable fashion"], answer: 1 },
      { q: "Which brand is known for its red and green stripe?", options: ["Burberry", "Gucci", "Prada", "Fendi"], answer: 1 },
      { q: "What is 'streetwear'?", options: ["Formal fashion", "Casual urban-inspired fashion", "Beachwear", "Sportswear"], answer: 1 },
      { q: "What is a 'capsule wardrobe'?", options: ["A small closet", "A collection of versatile basics", "Vintage collection", "Designer pieces only"], answer: 1 },
      { q: "Which brand is known for the iconic trench coat?", options: ["Gucci", "Burberry", "Louis Vuitton", "Balenciaga"], answer: 1 }
    ],
    medium: [
      { q: "Cristóbal Balenciaga was originally from which country?", options: ["France", "Italy", "Spain", "Portugal"], answer: 2 },
      { q: "The 'New Look' silhouette was introduced by which designer in 1947?", options: ["Coco Chanel", "Christian Dior", "Yves Saint Laurent", "Givenchy"], answer: 1 },
      { q: "Which fashion week happens first chronologically each year?", options: ["London", "Milan", "New York", "Paris"], answer: 2 },
      { q: "Which designer invented the wrap dress in the 1970s?", options: ["Halston", "Diane von Furstenberg", "Calvin Klein", "Oscar de la Renta"], answer: 1 },
      { q: "What does 'RTW' stand for in fashion?", options: ["Right to Wear", "Ready-to-Wear", "Runway to Wardrobe", "Retail Trade Week"], answer: 1 },
      { q: "Which luxury brand uses a horse and carriage as its logo?", options: ["Hermès", "Cartier", "Rolex", "Chanel"], answer: 0 },
      { q: "What is 'toile' used for in fashion?", options: ["Final garment fabric", "A test prototype of a design", "A type of print", "A weaving technique"], answer: 1 },
      { q: "Which designer is credited with popularizing the power suit for women?", options: ["Coco Chanel", "Giorgio Armani", "Ralph Lauren", "Calvin Klein"], answer: 1 },
      { q: "What is 'atelier' in the context of fashion?", options: ["A fashion magazine", "A designer's workshop", "A runway show", "A fabric store"], answer: 1 },
      { q: "What is 'bias cut' in garment construction?", options: ["Cutting fabric at a 45° angle", "Cutting fabric straight", "Cutting with a laser", "A pattern-making error"], answer: 0 },
      { q: "What is 'greige' in fashion?", options: ["A design technique", "A mix of grey and beige", "A sustainable fabric", "A vintage style"], answer: 1 },
      { q: "Versace's iconic Medusa logo symbolizes what?", options: ["Power and fatal beauty", "The founder's mother", "Greek origins of the brand", "The Gianni family crest"], answer: 0 },
      { q: "Which designer's passing in 2007 led LVMH to retain the brand under a new creative director?", options: ["Alexander McQueen", "Yves Saint Laurent", "John Galliano", "Gianni Versace"], answer: 1 },
      { q: "What is 'mercerization' in textile production?", options: ["Adding color to fabric", "Treatment making cotton lustrous and stronger", "A weaving technique", "A sustainable washing process"], answer: 1 },
      { q: "Which brand introduced the 'Speedy' bag?", options: ["Gucci", "Chanel", "Louis Vuitton", "Fendi"], answer: 2 }
    ],
    hard: [
      { q: "Paul Poiret liberated women from what garment in the early 1900s?", options: ["The bustle", "The corset", "The petticoat", "The crinoline"], answer: 1 },
      { q: "Which avant-garde Japanese designer created 'Comme des Garçons'?", options: ["Yohji Yamamoto", "Issey Miyake", "Rei Kawakubo", "Kenzo Takada"], answer: 2 },
      { q: "The term 'prêt-à-porter' was first used commercially in which decade?", options: ["1940s", "1950s", "1960s", "1970s"], answer: 1 },
      { q: "Which fashion house pioneered 'deconstructivism' — purposely unfinished, inside-out garments?", options: ["Maison Margiela", "Comme des Garçons", "Balenciaga", "Rick Owens"], answer: 0 },
      { q: "Elsa Schiaparelli famously collaborated with which surrealist artist on the Lobster Dress?", options: ["Picasso", "Salvador Dalí", "René Magritte", "Marcel Duchamp"], answer: 1 },
      { q: "What is a 'fichu' in historical fashion?", options: ["A triangular neck cloth", "A type of corset", "A hat style", "A shoe buckle"], answer: 0 },
      { q: "Which designer launched 'YSL Rive Gauche' — the first luxury ready-to-wear boutique — in 1966?", options: ["Christian Dior", "Hubert de Givenchy", "Yves Saint Laurent", "Pierre Cardin"], answer: 2 },
      { q: "The 'Gibson Girl' silhouette defined fashion in which decade?", options: ["1880s", "1890s–1900s", "1910s", "1920s"], answer: 1 },
      { q: "What is 'tambour work' in fashion embellishment?", options: ["A type of beading using a hooked needle", "A smocking technique", "A pleating method", "An appliqué style"], answer: 0 },
      { q: "Ossie Clark was a leading figure of which fashion movement?", options: ["The New Look era", "Swinging London 1960s", "The power suit 80s", "The minimalist 90s"], answer: 1 },
      { q: "What is 'matelassé' fabric?", options: ["A double-woven fabric with a raised quilted pattern", "A metallic woven fabric", "A single-layer lace fabric", "A dip-dyed fabric"], answer: 0 },
      { q: "Which country's traditional garment inspired the 'obi belt' trend in Western fashion?", options: ["China", "Korea", "Japan", "India"], answer: 2 },
      { q: "What textile is produced using the 'Macclesfield' weaving technique?", options: ["Silk twill ties", "Cotton voile", "Wool crepe", "Linen canvas"], answer: 0 },
      { q: "Coco Chanel's concept of 'total look' referred to what radical idea?", options: ["Accessories should match every garment component", "Women should dress identically to men", "Fashion should be completely monochromatic", "Garments should have no embellishment"], answer: 0 },
      { q: "What is the 'Balenciaga cocoon coat' structurally notable for?", options: ["Standing away from the body with no waist definition", "Built-in corsetry structure", "Reversible interior lining", "Asymmetric hemline cut"], answer: 0 }
    ]
  },
  sports: {
    name: "Sports", emoji: "⚽", color: "#34D399", accent: "#059669",
    bg: "linear-gradient(135deg, #34D399, #059669)", description: "Athletes, records & games",
    easy: [
      { q: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], answer: 1 },
      { q: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "France"], answer: 2 },
      { q: "In tennis, what is a 'love' score?", options: ["15 points", "30 points", "Zero points", "Match point"], answer: 2 },
      { q: "How many holes are in a standard golf course?", options: ["9", "12", "18", "24"], answer: 2 },
      { q: "How long is a standard marathon?", options: ["26.2 miles", "20 miles", "30 miles", "24 miles"], answer: 0 },
      { q: "Which sport uses a puck?", options: ["Football", "Hockey", "Polo", "Lacrosse"], answer: 1 },
      { q: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], answer: 1 },
      { q: "In which sport would you perform a 'slam dunk'?", options: ["Volleyball", "Tennis", "Basketball", "Baseball"], answer: 2 },
      { q: "How many players are in a cricket team?", options: ["9", "10", "11", "12"], answer: 2 },
      { q: "What color is the center of an archery target?", options: ["Red", "Blue", "Black", "Yellow"], answer: 3 },
      { q: "What is the term for three consecutive strikes in bowling?", options: ["Hat trick", "Turkey", "Spare", "Eagle"], answer: 1 },
      { q: "What sport is played at Wimbledon?", options: ["Badminton", "Squash", "Tennis", "Cricket"], answer: 2 },
      { q: "How many sets are in a standard volleyball match?", options: ["3", "4", "5", "6"], answer: 2 },
      { q: "What is the highest score in a single dart throw?", options: ["25", "50", "60", "100"], answer: 2 },
      { q: "Which country invented basketball?", options: ["USA", "Canada", "UK", "Australia"], answer: 1 }
    ],
    medium: [
      { q: "What is the diameter of a basketball hoop in inches?", options: ["16 inches", "18 inches", "20 inches", "22 inches"], answer: 1 },
      { q: "Which athlete has won the most Olympic gold medals of all time?", options: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], answer: 1 },
      { q: "What is the maximum break in snooker?", options: ["145", "147", "150", "155"], answer: 1 },
      { q: "Which country hosted the first modern Olympic Games in 1896?", options: ["France", "UK", "Greece", "Germany"], answer: 2 },
      { q: "In tennis, what is a 'bagel' slang for?", options: ["A double fault", "Winning a set 6-0", "An ace serve", "A tiebreak win"], answer: 1 },
      { q: "How many Grand Slam titles did Roger Federer win in his career?", options: ["18", "19", "20", "21"], answer: 2 },
      { q: "What is the offside rule in football decided by?", options: ["The referee's judgment", "The last outfield defender", "The goalkeeper's position", "The center line"], answer: 1 },
      { q: "In cricket, what is a 'googly'?", options: ["A spin bowler's deceptive delivery", "A six hit behind the wicket", "A type of batting stance", "An umpire's signal"], answer: 0 },
      { q: "How many points is a try worth in rugby union?", options: ["3", "4", "5", "6"], answer: 2 },
      { q: "In which year did South Africa win their first Rugby World Cup?", options: ["1991", "1995", "1999", "2003"], answer: 1 },
      { q: "What does 'ERA' stand for in baseball statistics?", options: ["Earned Run Average", "Error Rate Analysis", "Extra Run Attempt", "Earned Record Average"], answer: 0 },
      { q: "What is 'la belle' in fencing terminology?", options: ["A decisive final point", "A perfect parry", "An opening stance", "A disqualification"], answer: 0 },
      { q: "Which sport uses the term 'stimpmeter'?", options: ["Bowling", "Golf", "Billiards", "Cricket"], answer: 1 },
      { q: "In football, what does VAR stand for?", options: ["Video Assisted Referee", "Visual Analysis Review", "Video Action Replay", "Virtual Assistance Regulation"], answer: 0 },
      { q: "What is the name of the trophy for Formula 1's Constructors' Championship?", options: ["The World Trophy", "The Manufacturers Trophy", "The FIA Trophy", "The Constructors' Cup"], answer: 1 }
    ],
    hard: [
      { q: "In the 1904 Olympics, Frederick Lorz was disqualified from the marathon for what?", options: ["Using drugs", "Hitching a ride in a car for 11 miles", "Starting early", "Cutting through a building"], answer: 1 },
      { q: "What is the Fosbury Flop technique used in?", options: ["Swimming", "High jump", "Pole vault", "Long jump"], answer: 1 },
      { q: "Which country has won the most Davis Cup titles in tennis?", options: ["USA", "Australia", "Spain", "France"], answer: 0 },
      { q: "The 'Duckworth-Lewis-Stern method' in cricket is used for what?", options: ["Calculating bowling speed", "Resetting targets in rain-interrupted matches", "Measuring pitch conditions", "Adjudicating DRS reviews"], answer: 1 },
      { q: "Which boxer was nicknamed 'The Mongoose' — Ali's craftiest opponent?", options: ["Joe Frazier", "Ken Norton", "Archie Moore", "George Foreman"], answer: 2 },
      { q: "In cycling, what does 'GC' stand for in Tour de France standings?", options: ["Grand Circuit", "General Classification", "Group Contender", "Grand Competition"], answer: 1 },
      { q: "What is 'épée' in fencing?", options: ["The thrusting sword targeting the entire body", "A parrying technique", "A type of mask", "The lightest scoring zone"], answer: 0 },
      { q: "Which NFL team went 16-0 in the regular season but lost the Super Bowl?", options: ["New England Patriots 2007", "San Francisco 49ers 1984", "Chicago Bears 1985", "Miami Dolphins 1972"], answer: 0 },
      { q: "How many dimples does a regulation golf ball have?", options: ["256", "336", "432", "500"], answer: 1 },
      { q: "What is the total number of squares on a standard draughts (checkers) board?", options: ["32", "48", "64", "100"], answer: 2 },
      { q: "The 'Bosman ruling' changed football transfers forever — which country was Bosman from?", options: ["Germany", "Belgium", "France", "Netherlands"], answer: 1 },
      { q: "In rowing, what does 'cox' refer to?", options: ["A rowing stroke technique", "The coxswain who steers the boat", "A type of oar grip", "A safety regulation"], answer: 1 },
      { q: "The 'Miracle on Ice' in the 1980 Winter Olympics involved the USA defeating which team?", options: ["Canada", "Sweden", "Czechoslovakia", "Soviet Union"], answer: 3 },
      { q: "What is the exact distance in yards of a standard polo field?", options: ["200", "274", "300", "320"], answer: 1 },
      { q: "In snooker, what color ball is worth 6 points?", options: ["Blue", "Pink", "Brown", "Black"], answer: 1 }
    ]
  },
  movies: {
    name: "Movies", emoji: "🎬", color: "#FBBF24", accent: "#D97706",
    bg: "linear-gradient(135deg, #FBBF24, #D97706)", description: "Cinema, directors & classics",
    easy: [
      { q: "Which movie features 'May the Force be with you'?", options: ["Star Trek", "Star Wars", "The Matrix", "Interstellar"], answer: 1 },
      { q: "Who directed 'Titanic'?", options: ["Spielberg", "Nolan", "James Cameron", "Ridley Scott"], answer: 2 },
      { q: "What is the highest-grossing film of all time?", options: ["Avengers: Endgame", "Titanic", "Avatar", "The Lion King"], answer: 2 },
      { q: "Which film has Tom Hanks saying 'Life is like a box of chocolates'?", options: ["Cast Away", "Forrest Gump", "The Terminal", "Philadelphia"], answer: 1 },
      { q: "Which studio produced the Toy Story franchise?", options: ["DreamWorks", "Disney", "Pixar", "Universal"], answer: 2 },
      { q: "What is the fictional kingdom in Frozen?", options: ["Narnia", "Arendelle", "Agrabah", "Zootopia"], answer: 1 },
      { q: "Which actor played Iron Man in the MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: 1 },
      { q: "Who voiced Simba in the original Lion King?", options: ["Eddie Murphy", "Matthew Broderick", "James Earl Jones", "Jeremy Irons"], answer: 1 },
      { q: "Which film features Heath Ledger as The Joker?", options: ["Batman Begins", "The Dark Knight", "Suicide Squad", "Joker"], answer: 1 },
      { q: "Which movie features 'Let It Go'?", options: ["Tangled", "Moana", "Frozen", "Brave"], answer: 2 },
      { q: "In Harry Potter, what sport is played on broomsticks?", options: ["Quodpot", "Quidditch", "Broomball", "Seekball"], answer: 1 },
      { q: "Who directed Inception and Interstellar?", options: ["Denis Villeneuve", "Wes Anderson", "Christopher Nolan", "David Fincher"], answer: 2 },
      { q: "What is the name of the spaceship in Alien?", options: ["Enterprise", "Nostromo", "Discovery", "Serenity"], answer: 1 },
      { q: "Which film won the first ever Academy Award for Best Picture?", options: ["Gone with the Wind", "Wings", "Citizen Kane", "Casablanca"], answer: 1 },
      { q: "What genre is 'Get Out'?", options: ["Comedy", "Romance", "Horror/Thriller", "Action"], answer: 2 }
    ],
    medium: [
      { q: "Which three films share the record of 11 Academy Award wins?", options: ["Titanic, LOTR: Return of the King, Ben-Hur", "Gone with the Wind, Schindler's List, Braveheart", "Avatar, The Godfather, Star Wars", "Star Wars, Braveheart, Chicago"], answer: 0 },
      { q: "Stanley Kubrick directed all EXCEPT which film?", options: ["Full Metal Jacket", "A Clockwork Orange", "Apocalypse Now", "The Shining"], answer: 2 },
      { q: "What film technique did Orson Welles pioneer in Citizen Kane?", options: ["Slow motion", "Deep focus photography", "Handheld camera", "Color grading"], answer: 1 },
      { q: "Which 1999 film popularized the 'bullet time' visual effect?", options: ["Dark City", "The Matrix", "eXistenZ", "Strange Days"], answer: 1 },
      { q: "Which director has a signature cameo in almost every one of his films?", options: ["Martin Scorsese", "Alfred Hitchcock", "Wes Anderson", "Tim Burton"], answer: 1 },
      { q: "The 'Kuleshov Effect' in film editing is about what?", options: ["Color theory in film", "How context changes the meaning of an image", "Camera movement psychology", "Sound design emotion"], answer: 1 },
      { q: "Which French New Wave director made 'Breathless' in 1960?", options: ["François Truffaut", "Jean-Luc Godard", "Agnès Varda", "Louis Malle"], answer: 1 },
      { q: "What is the 'dolly zoom' technique?", options: ["Dutch angle framing", "Camera zooms while physically moving in opposite direction", "A tracking shot", "A whip pan"], answer: 1 },
      { q: "Which film is NOT a Coen Brothers movie?", options: ["Fargo", "No Country for Old Men", "Blood Simple", "There Will Be Blood"], answer: 3 },
      { q: "What is 'mise-en-scène' in filmmaking?", options: ["The film score arrangement", "Everything visible within the frame", "Post-production editing", "The screenplay format"], answer: 1 },
      { q: "Akira Kurosawa's 'Seven Samurai' was remade as which American western?", options: ["The Magnificent Seven", "The Wild Bunch", "Unforgiven", "High Noon"], answer: 0 },
      { q: "Which 1927 film is considered the first feature-length sound film?", options: ["The General", "The Jazz Singer", "Metropolis", "Sunrise"], answer: 1 },
      { q: "What does 'ADR' stand for in post-production?", options: ["Audio Design Room", "Automated Dialogue Replacement", "Advanced Digital Rendering", "Audio Director's Review"], answer: 1 },
      { q: "Which film is NOT part of Tarantino's 'rewritten history' films?", options: ["Inglourious Basterds", "Django Unchained", "Once Upon a Time in Hollywood", "Pulp Fiction"], answer: 3 },
      { q: "What is a 'MacGuffin' in film terminology?", options: ["A plot twist", "An object that motivates characters but has no inherent story importance", "An unreliable narrator", "A false story resolution"], answer: 1 }
    ],
    hard: [
      { q: "In 'Mulholland Drive', David Lynch uses which narrative technique?", options: ["Linear storytelling with flashbacks", "Dream-logic non-linear narrative", "Documentary realism", "Unreliable narrator voiceover"], answer: 1 },
      { q: "What is the 'Odessa Steps' sequence in Battleship Potemkin famous for demonstrating?", options: ["First color in Soviet film", "Eisenstein's montage theory made visual", "First underwater scene in cinema", "Birth of the tracking shot"], answer: 1 },
      { q: "In Carl Dreyer's 'The Passion of Joan of Arc', what made its close-ups revolutionary?", options: ["Color grading on skin tones", "Extreme close-ups without makeup revealing raw emotion", "A wide angle lens throughout", "Silent intertitles completely removed"], answer: 1 },
      { q: "Federico Fellini's '8½' title refers to what?", options: ["The number of films he had directed at the time", "The number of main characters", "His age when he started filmmaking", "The running time in hours"], answer: 0 },
      { q: "Which film theorist coined the 'auteur theory'?", options: ["Sergei Eisenstein", "André Bazin", "François Truffaut", "Siegfried Kracauer"], answer: 2 },
      { q: "What is the 'Z-axis' in cinematography?", options: ["Depth — movement toward or away from camera", "Vertical camera movement", "Color temperature axis", "Sound axis in Dolby mix"], answer: 0 },
      { q: "Andrei Tarkovsky's 'Stalker' is based on a novel by which authors?", options: ["Dostoevsky and Tolstoy", "Arkady and Boris Strugatsky", "Isaac Asimov", "Philip K. Dick"], answer: 1 },
      { q: "Which film pioneered CGI 'synthespian' characters as early as 1985?", options: ["Tron", "The Last Starfighter", "Willow", "Young Sherlock Holmes"], answer: 3 },
      { q: "What is the 'Bresson model' acting technique?", options: ["Method acting from psychological trauma", "Non-professional 'models' with suppressed expression", "Improvisation-based performance", "Stage-trained theatrical acting"], answer: 1 },
      { q: "In 'Persona' by Bergman, the two faces merging represents what?", options: ["An editing error", "Identity dissolution and psychological doubling", "A continuity mistake", "A supernatural element"], answer: 1 },
      { q: "Which sound designer pioneered 'sound design' as an art form starting with Apocalypse Now?", options: ["Ben Burtt", "Alan Splet", "Walter Murch", "Gary Rydstrom"], answer: 2 },
      { q: "What German Expressionist technique involves distorted sets reflecting psychological states?", options: ["Chiaroscuro", "Kammerspiel", "Expressionistic mise-en-scène", "Neue Sachlichkeit"], answer: 2 },
      { q: "What experimental Andy Warhol film consists entirely of a man sleeping for 5+ hours?", options: ["Blow Job", "Empire", "Sleep", "Chelsea Girls"], answer: 2 },
      { q: "The 'Rashomon effect' from Kurosawa's film describes what narrative phenomenon?", options: ["A story told in reverse", "The same event described differently by multiple witnesses", "An unreliable narrator revealed at the end", "Parallel timelines converging"], answer: 1 },
      { q: "Which cinematographer won back-to-back Oscars for 'Blade Runner 2049' and '1917'?", options: ["Emmanuel Lubezki", "Roger Deakins", "Hoyte van Hoytema", "Rodrigo Prieto"], answer: 1 }
    ]
  },
  food: {
    name: "Food", emoji: "🍜", color: "#FB923C", accent: "#EA580C",
    bg: "linear-gradient(135deg, #FB923C, #EA580C)", description: "Cuisine, flavors & culture",
    easy: [
      { q: "Which country is sushi originally from?", options: ["China", "Korea", "Japan", "Thailand"], answer: 2 },
      { q: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Mango", "Lime"], answer: 1 },
      { q: "Which spice gives curry its yellow color?", options: ["Cumin", "Paprika", "Turmeric", "Saffron"], answer: 2 },
      { q: "Which country invented pizza?", options: ["USA", "Greece", "Italy", "France"], answer: 2 },
      { q: "What is the main ingredient in hummus?", options: ["Lentils", "Black beans", "Chickpeas", "Edamame"], answer: 2 },
      { q: "What does 'al dente' mean?", options: ["Well done", "Firm to the bite", "Very soft", "Crispy"], answer: 1 },
      { q: "Which cheese is traditionally used in a Margherita pizza?", options: ["Cheddar", "Parmesan", "Mozzarella", "Brie"], answer: 2 },
      { q: "Which fruit is known as the 'king of fruits'?", options: ["Mango", "Durian", "Jackfruit", "Papaya"], answer: 1 },
      { q: "Which country is famous for 'dim sum'?", options: ["Japan", "Vietnam", "China", "Thailand"], answer: 2 },
      { q: "Which nut is used to make marzipan?", options: ["Walnut", "Hazelnut", "Almond", "Pistachio"], answer: 2 },
      { q: "What type of pasta is shaped like little ears?", options: ["Penne", "Orecchiette", "Farfalle", "Rigatoni"], answer: 1 },
      { q: "What is 'umami'?", options: ["A Japanese dish", "The fifth basic taste", "A cooking technique", "A type of sauce"], answer: 1 },
      { q: "Which country invented croissants?", options: ["France", "Austria", "Belgium", "Switzerland"], answer: 1 },
      { q: "What is 'blanching' in cooking?", options: ["Slow roasting", "Brief boiling then cooling", "Deep frying", "Marinating"], answer: 1 },
      { q: "What is the base of a Caesar salad dressing?", options: ["Mayo", "Vinegar", "Worcestershire & anchovy", "Olive oil"], answer: 2 }
    ],
    medium: [
      { q: "What is the Maillard reaction?", options: ["Caramelization of sugars", "Browning from amino acids and heat", "Emulsification of fats", "Gluten formation"], answer: 1 },
      { q: "Which wine region in France is known for Cabernet Sauvignon?", options: ["Burgundy", "Champagne", "Bordeaux", "Alsace"], answer: 2 },
      { q: "What is 'mise en place' in culinary terms?", options: ["A French dessert", "Everything in its place before cooking", "A plating technique", "A type of sauce"], answer: 1 },
      { q: "Sous vide cooking involves what technique?", options: ["High-heat flash cooking", "Slow cooking in vacuum-sealed bags in water", "Smoke infusion", "Pressure cooking"], answer: 1 },
      { q: "Which fermentation process produces kimchi?", options: ["Alcoholic fermentation", "Lacto-fermentation", "Acetic acid fermentation", "Mold fermentation"], answer: 1 },
      { q: "What is 'chiffonade' as a cutting technique?", options: ["Rough chopping", "Thin ribbon slices of leafy vegetables", "Brunoise dice cut", "Julienne of root vegetables"], answer: 1 },
      { q: "In molecular gastronomy, 'spherification' creates what?", options: ["Edible liquid-filled spheres", "Smoke infusions", "Freeze-dried powders", "Color-changing foods"], answer: 0 },
      { q: "Which region of Italy produces Parmigiano-Reggiano?", options: ["Tuscany", "Emilia-Romagna", "Lombardy", "Veneto"], answer: 1 },
      { q: "What is 'dashi' in Japanese cuisine?", options: ["Fermented soybean paste", "Stock from kombu and bonito flakes", "Pickled vegetables", "A type of noodle"], answer: 1 },
      { q: "What is cooking 'en papillote'?", options: ["Deep frying in oil", "Cooking in a parchment paper parcel", "Braising in wine", "Smoking over wood chips"], answer: 1 },
      { q: "What is 'tempering' chocolate?", options: ["Melting chocolate", "A heating/cooling process for stable crystal structure", "Adding emulsifiers", "Conching the cocoa"], answer: 1 },
      { q: "Which acid gives sourdough its characteristic tang?", options: ["Citric acid", "Lactic and acetic acid", "Tartaric acid", "Malic acid"], answer: 1 },
      { q: "In French cuisine, what is a 'beurre blanc'?", options: ["A white cream sauce", "An emulsified butter sauce with white wine reduction", "A cold butter compound", "A white chocolate glaze"], answer: 1 },
      { q: "What protein structure gives bread its elasticity?", options: ["Casein", "Gluten", "Albumin", "Myosin"], answer: 1 },
      { q: "What is 'umeboshi' in Japanese cuisine?", options: ["A type of ramen", "Pickled Japanese plums", "A fermented soy sauce", "Dried seaweed"], answer: 1 }
    ],
    hard: [
      { q: "What is 'transglutaminase' sometimes called in molecular gastronomy?", options: ["Chef's acid", "Meat glue", "Liquid nitrogen paste", "Enzyme binder"], answer: 1 },
      { q: "What is 'Périgord' specifically associated with in French haute cuisine?", options: ["White truffles from Normandy", "Black truffles and foie gras from the Périgord region", "Oysters from Brittany", "Mustard from Dijon"], answer: 1 },
      { q: "In fermentation, what is the role of 'koji' mold?", options: ["Adds sour flavor", "Breaks down starches into sugars for sake, miso and soy sauce", "Prevents bacterial contamination", "Creates umami in fish sauce"], answer: 1 },
      { q: "What is 'Escoffier's brigade system' in professional kitchens?", options: ["A recipe standardization method", "A hierarchical kitchen team structure he codified", "A plating philosophy", "A sanitation protocol"], answer: 1 },
      { q: "What chemical compound gives chillies their heat?", options: ["Piperine", "Allicin", "Capsaicin", "Cinnamaldehyde"], answer: 2 },
      { q: "In wine, what does 'brettanomyces' (Brett) produce?", options: ["Fruity esters", "Barnyard/leather aromas considered a fault or complexity", "High tannins", "Excessive residual sugar"], answer: 1 },
      { q: "What causes bread to 'stale' over time?", options: ["Moisture loss only", "Retrogradation — starch crystallizing back to ordered structure", "Continued yeast activity", "Oxidation of gluten proteins"], answer: 1 },
      { q: "Which enzyme in pineapple prevents gelatin from setting?", options: ["Papain", "Bromelain", "Actinidin", "Ficin"], answer: 1 },
      { q: "What is Jean Anthelme Brillat-Savarin most famous for?", options: ["Inventing French mother sauces", "Writing 'The Physiology of Taste' — the first food philosophy book", "Creating the tasting menu format", "Founding the Michelin Guide"], answer: 1 },
      { q: "The cooking method 'à la nage' refers to what?", options: ["Cooking in rich cream sauce", "Poaching in aromatic court-bouillon served as broth", "Deep frying in clarified butter", "Baking in a salt crust"], answer: 1 },
      { q: "What is 'torchon' preparation in foie gras?", options: ["Pan-searing at high heat", "Rolling and poaching in a cloth", "Air-drying over 48 hours", "Marinating in armagnac and pressing"], answer: 1 },
      { q: "Which Maillard reaction byproducts are considered potentially carcinogenic at high temperatures?", options: ["Acrylamide only", "Furans only", "Heterocyclic amines only", "All of the above"], answer: 3 },
      { q: "What is 'hydrocolloid' used for in modernist cuisine?", options: ["Adding color without flavor", "Creating gels, foams and thickeners from plant polymers", "Infusing flavors via pressure", "Separating emulsions"], answer: 1 },
      { q: "In Japanese knife terminology, what is a 'yanagiba' used for?", options: ["Chopping vegetables with a push cut", "Slicing raw fish in one smooth pull cut", "Breaking down fish bones", "Peeling citrus zest"], answer: 1 },
      { q: "What is 'lacto-fermentation' at a chemical level?", options: ["Bacteria converting sugars into lactic acid, lowering pH", "Yeast producing alcohol from sugars", "Mold breaking down proteins", "Vinegar bacteria converting alcohol to acetic acid"], answer: 0 }
    ]
  },
  science: {
    name: "Science", emoji: "🔬", color: "#60A5FA", accent: "#2563EB",
    bg: "linear-gradient(135deg, #60A5FA, #2563EB)", description: "Facts, discoveries & nature",
    easy: [
      { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
      { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
      { q: "What planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Saturn", "Mars"], answer: 3 },
      { q: "Which gas makes up most of Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: 2 },
      { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], answer: 2 },
      { q: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Quartz"], answer: 2 },
      { q: "What force keeps planets in orbit?", options: ["Magnetism", "Gravity", "Friction", "Nuclear force"], answer: 1 },
      { q: "What is the process by which plants make food?", options: ["Respiration", "Transpiration", "Photosynthesis", "Fermentation"], answer: 2 },
      { q: "Which scientist developed the theory of general relativity?", options: ["Newton", "Bohr", "Einstein", "Hawking"], answer: 2 },
      { q: "How many chromosomes do humans have?", options: ["23", "44", "46", "48"], answer: 2 },
      { q: "What is the speed of light approximately?", options: ["200,000 km/s", "299,792 km/s", "350,000 km/s", "150,000 km/s"], answer: 1 },
      { q: "What is the most abundant element in the universe?", options: ["Oxygen", "Carbon", "Helium", "Hydrogen"], answer: 3 },
      { q: "What is absolute zero in Celsius?", options: ["-100°C", "-200°C", "-273°C", "-350°C"], answer: 2 },
      { q: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
      { q: "What is the atomic number of carbon?", options: ["4", "6", "8", "12"], answer: 1 }
    ],
    medium: [
      { q: "What is the Heisenberg Uncertainty Principle?", options: ["Energy cannot be created or destroyed", "You cannot simultaneously know exact position and momentum of a particle", "Light behaves as wave and particle", "Mass increases with velocity"], answer: 1 },
      { q: "What is the half-life of Carbon-14?", options: ["570 years", "5,730 years", "57,300 years", "573 years"], answer: 1 },
      { q: "What is 'dark matter'?", options: ["Black holes", "Invisible matter with gravitational effects that doesn't interact with light", "Antimatter", "Dense gas clouds"], answer: 1 },
      { q: "In DNA, which base pairs with Adenine?", options: ["Guanine", "Cytosine", "Thymine", "Uracil"], answer: 2 },
      { q: "What is the Doppler Effect?", options: ["Light bending around mass", "Change in wave frequency due to relative motion", "Sound absorption in vacuum", "Electromagnetic interference"], answer: 1 },
      { q: "What subatomic particles make up a proton?", options: ["Electrons and neutrons", "Two up quarks and one down quark", "Three down quarks", "One up quark and two down quarks"], answer: 1 },
      { q: "What is 'entropy' in thermodynamics?", options: ["Total energy in a system", "Measure of disorder or randomness", "Heat transfer efficiency", "Kinetic energy of molecules"], answer: 1 },
      { q: "Which law states pressure and volume of a gas are inversely proportional?", options: ["Charles's Law", "Avogadro's Law", "Boyle's Law", "Gay-Lussac's Law"], answer: 2 },
      { q: "What is the function of the hippocampus?", options: ["Controls heart rate", "Processes visual information", "Memory formation and spatial navigation", "Regulates breathing"], answer: 2 },
      { q: "What is 'nuclear fusion'?", options: ["Splitting atoms to release energy", "Combining atomic nuclei to release energy", "Radioactive decay of atoms", "A fission chain reaction"], answer: 1 },
      { q: "What is the Coriolis Effect?", options: ["Ocean tides caused by the moon", "Deflection of moving objects due to Earth's rotation", "Pressure changes with altitude", "Magnetic field variations"], answer: 1 },
      { q: "In chemistry, what is an 'isomer'?", options: ["A radioactive isotope", "Two molecules with same formula but different structure", "A negatively charged ion", "An element with different neutron counts"], answer: 1 },
      { q: "What is the key difference between mitosis and meiosis?", options: ["Mitosis produces 4 cells, meiosis produces 2", "Mitosis for growth (2 identical cells), meiosis for reproduction (4 unique cells)", "They are the same process", "Mitosis only occurs in plants"], answer: 1 },
      { q: "What is 'bioluminescence'?", options: ["UV light absorption in plants", "Light produced by living organisms via chemical reactions", "Reflection of moonlight in water", "Heat radiation from organisms"], answer: 1 },
      { q: "What is the pH of pure water?", options: ["6", "7", "8", "9"], answer: 1 }
    ],
    hard: [
      { q: "What does the 'Chandrasekhar limit' define?", options: ["Maximum mass of a stable white dwarf star", "Minimum distance from a black hole", "Speed at which light bends near mass", "The age of the universe"], answer: 0 },
      { q: "In quantum mechanics, what is 'superposition'?", options: ["Layers of atomic structure", "A particle existing in multiple states simultaneously until observed", "Interference between two waves", "The spin of an electron"], answer: 1 },
      { q: "What is the 'chirality' of a molecule?", options: ["Its electrical charge distribution", "A property where a molecule is non-superimposable on its mirror image", "The number of chiral centers only", "Its rotational symmetry"], answer: 1 },
      { q: "What does the 'Pauli Exclusion Principle' state?", options: ["Two particles cannot occupy the same space", "No two fermions can occupy the same quantum state simultaneously", "Particles with opposite spin attract", "Energy is quantized in discrete levels"], answer: 1 },
      { q: "The Krebs cycle occurs in which part of the cell?", options: ["Nucleus", "Cytoplasm", "Mitochondrial matrix", "Endoplasmic reticulum"], answer: 2 },
      { q: "What is 'quantum entanglement'?", options: ["Particles vibrating at the same frequency", "Two particles sharing quantum states — measuring one instantly affects the other", "Electrons sharing orbital shells", "Nuclear binding of particles"], answer: 1 },
      { q: "What does the 'Standard Model' of particle physics NOT include?", options: ["Quarks", "Leptons", "Gravity", "Gauge bosons"], answer: 2 },
      { q: "In genetics, what is 'epistasis'?", options: ["A type of mutation", "When one gene masks or modifies another gene's expression", "The physical expression of a genotype", "A chromosomal deletion"], answer: 1 },
      { q: "What is 'frame-dragging' in general relativity?", options: ["Light bending around mass", "Rotating massive objects dragging spacetime around them", "Time dilation near massive objects", "Gravitational wave propagation"], answer: 1 },
      { q: "What is the 'Mpemba Effect'?", options: ["Cold objects absorb more heat", "Hot water can freeze faster than cold water under certain conditions", "Ice forms from the inside outward", "Supercooled water resists freezing"], answer: 1 },
      { q: "What is 'CRISPR-Cas9' in molecular biology?", options: ["A cancer drug delivery system", "A gene-editing tool using RNA to guide cuts in DNA", "A protein synthesis pathway", "A viral vector for gene therapy"], answer: 1 },
      { q: "What is the difference between Type I and Type II supernovae?", options: ["Size of the resulting remnant", "Type I lacks hydrogen lines (white dwarf), Type II has them (massive star collapse)", "Brightness at peak luminosity", "Distance from Earth"], answer: 1 },
      { q: "What is the 'Many-Worlds Interpretation' of quantum mechanics?", options: ["Multiple universes explained by string theory", "Every quantum event causes a branching into parallel realities", "Particles exist in all possible worlds simultaneously", "A disproven interpretation replaced by Copenhagen"], answer: 1 },
      { q: "What is 'allosteric regulation' in enzyme biology?", options: ["Competitive inhibition at active sites", "Binding at a non-active site that changes enzyme shape and activity", "Covalent modification of enzyme structure", "Temperature-based enzyme denaturation"], answer: 1 },
      { q: "In cosmology, what is the 'Hubble tension'?", options: ["The difficulty of measuring galaxy distances", "A discrepancy between early and late universe measurements of the Hubble constant", "The acceleration of universe expansion", "Tension between dark matter and dark energy models"], answer: 1 }
    ]
  }
};
